import type { Vehicle } from "./types";

/**
 * Current stock, transcribed from the dealership's own inventory API
 * (`/api/vehicles` on the previous site) on 10 September 2026.
 *
 * Rules followed when transcribing:
 *  - Price, mileage, year, fuel, transmission, colour, body type, HPI status,
 *    warranty months, description and feature lists are copied verbatim.
 *  - `engine`, `interior` and `serviceHistory` are only set where the
 *    dealership's own feature list or description states them. Nothing is
 *    inferred from the model name.
 *  - Registration, power, doors and seats are omitted entirely — the source
 *    holds no values for them, so the vehicle page shows no such rows.
 *  - Every `images` array is empty because the dealership has not yet supplied
 *    photography. See `PHOTOGRAPHY.md` for how to add it.
 *
 * This file is the seam. Replacing it with a database or feed means changing
 * `repository.ts` only — no component reads from here directly.
 */
export const vehicles: Vehicle[] = [
  {
    id: "v006",
    slug: "rolls-royce-dawn-2016",
    title: "Rolls-Royce Dawn",
    make: "Rolls-Royce",
    model: "Dawn",
    year: 2016,
    mileage: 28000,
    price: 30000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Convertible",
    colour: "Arctic White",
    engine: "6.6L Twin-Turbo V12",
    interior: "Cream leather with navy hood",
    hpiClear: true,
    warrantyMonths: 12,
    ulezCompliant: null,
    description:
      "The Rolls-Royce Dawn is the most social of super-luxury cars — an open-top four-seater that makes an entrance everywhere it goes. This stunning example in arctic white with a navy hood and cream leather interior is simply spectacular. The whisper-quiet fabric roof opens in 22 seconds, transforming this masterpiece into the ultimate open-air experience.",
    features: [
      "6.6L Twin-Turbo V12",
      "Bespoke Audio System",
      "Starlight Headliner",
      "Suicide Rear Doors",
      "Heated & Massaging Seats",
      "Night Vision",
      "Wi-Fi Hotspot",
      "Spirit of Ecstasy",
    ],
    images: [],
    /**
     * Sample library image. This is the one vehicle where a commercially
     * licensed, colour-accurate photograph of the correct model exists — a
     * white Dawn with a navy hood, matching the description above. Kept so the
     * gallery, lightbox and credit line have a real image to render, and so
     * the client can see the library-image treatment before deciding whether
     * to extend it. See PHOTOGRAPHY.md.
     */
    libraryImages: [
      {
        src: "/vehicles/rolls-royce-dawn-2016/exterior-front.webp",
        alt: "Rolls-Royce Dawn convertible in white with a navy hood, front three-quarter view",
        width: 1023,
        height: 639,
        provenance: "library",
        credit: {
          author: "crash71100",
          license: "CC0 1.0",
          licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
          sourceUrl: "https://www.flickr.com/photos/152930510@N02/45293854451",
        },
      },
    ],
    status: "available",
    featured: true,
    listedAt: "2026-05-02T01:25:31.959Z",
  },
  {
    id: "v004",
    slug: "rolls-royce-corniche-1999",
    title: "Rolls-Royce Corniche",
    make: "Rolls-Royce",
    model: "Corniche",
    year: 1999,
    mileage: 42000,
    price: 60000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Convertible",
    colour: "Silver Seraph",
    interior: "Connolly leather with burr walnut dashboard",
    serviceHistory: "Comprehensive history file",
    hpiClear: true,
    warrantyMonths: 0,
    ulezCompliant: null,
    description:
      "One of the most desirable and elegant convertibles ever produced, the Rolls-Royce Corniche is a true classic motorcar. Hand-built with unrivalled attention to detail, this example features the sumptuous Connolly leather interior and burr walnut dashboard that define Rolls-Royce craftsmanship at its finest.",
    features: [
      "Classic Rolls-Royce Pedigree",
      "Connolly Leather Interior",
      "Burr Walnut Dashboard",
      "Power Hood",
      "HPI Clear",
      "Comprehensive History File",
      "Matching Numbers",
    ],
    images: [],
    libraryImages: [],
    status: "available",
    featured: true,
    listedAt: "2026-05-02T01:25:31.959Z",
  },
  {
    id: "v003",
    slug: "mercedes-benz-sl63-amg-2016",
    title: "Mercedes-Benz SL63 AMG",
    make: "Mercedes-Benz",
    model: "SL63 AMG",
    year: 2016,
    mileage: 38000,
    price: 40000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Convertible",
    colour: "Obsidian Black",
    engine: "5.5L Biturbo V8",
    interior: "Red leather",
    hpiClear: true,
    warrantyMonths: 6,
    ulezCompliant: null,
    description:
      "The SL63 AMG is the definitive grand tourer — breathtaking to look at and even more thrilling to drive. This 2016 example features the twin-turbo V8, AMG Performance exhaust and retractable hardtop. Finished in obsidian black with a red leather interior, it commands attention wherever it goes.",
    features: [
      "5.5L Biturbo V8",
      "AMG Performance Exhaust",
      "Retractable Hardtop",
      "Red Leather Interior",
      "Bang & Olufsen Audio",
      "Magic Sky Control",
      "Heated & Ventilated Seats",
      "AMG Driver's Package",
    ],
    images: [],
    libraryImages: [],
    status: "available",
    featured: true,
    listedAt: "2026-05-02T01:25:31.959Z",
  },
  {
    id: "v007",
    slug: "porsche-macan-s-2014",
    title: "Porsche Macan S",
    make: "Porsche",
    model: "Macan S",
    year: 2014,
    mileage: 62000,
    price: 25000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    colour: "Jet Black Metallic",
    engine: "3.0L Twin-Turbo V6",
    serviceHistory: "Full Porsche service history",
    hpiClear: true,
    warrantyMonths: 3,
    ulezCompliant: null,
    description:
      "The Porsche Macan S is the benchmark for the premium compact SUV segment — combining Porsche sports car DNA with everyday practicality. This 2014 example in jet black metallic is in excellent condition with a full Porsche service history, making it a superb choice for the discerning driver.",
    features: [
      "3.0L Twin-Turbo V6",
      "Full Porsche Service History",
      "HPI Clear",
      "Sport Chrono Package",
      "PASM Suspension",
      "BOSE Sound System",
      "Panoramic Roof",
      '20" Macan Turbo Wheels',
    ],
    images: [],
    libraryImages: [],
    status: "available",
    featured: true,
    listedAt: "2026-05-02T01:25:31.959Z",
  },
  {
    id: "v005",
    slug: "rolls-royce-silver-shadow-1978",
    title: "Rolls-Royce Silver Shadow",
    make: "Rolls-Royce",
    model: "Silver Shadow",
    year: 1978,
    mileage: 58000,
    price: 20000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Saloon",
    colour: "Silver",
    interior: "Original",
    serviceHistory: "Comprehensive history",
    hpiClear: true,
    warrantyMonths: 0,
    ulezCompliant: null,
    description:
      "An iconic piece of British motoring history — the Rolls-Royce Silver Shadow is one of the most recognisable and celebrated classic cars in the world. This beautifully preserved example is a collector's dream, offering the serenity and prestige that only a Rolls-Royce can provide.",
    features: [
      "Classic British Icon",
      "Original Interior",
      "Comprehensive History",
      "HPI Clear",
      "Matching Numbers",
      "Collector Quality",
    ],
    images: [],
    libraryImages: [],
    status: "available",
    featured: false,
    listedAt: "2026-05-02T01:25:31.959Z",
  },
  {
    id: "v001",
    slug: "jaguar-xf-2012",
    title: "Jaguar XF",
    make: "Jaguar",
    model: "XF",
    year: 2012,
    mileage: 68000,
    price: 16000,
    fuel: "Diesel",
    transmission: "Automatic",
    bodyType: "Saloon",
    colour: "Midnight Black",
    interior: "Leather",
    serviceHistory: "Full service history",
    hpiClear: true,
    warrantyMonths: 3,
    ulezCompliant: null,
    description:
      "A stunning example of the iconic Jaguar XF in deep midnight black. This executive saloon presents beautifully inside and out with a refined interior, smooth automatic gearbox and the effortless performance Jaguar is renowned for. Full service history, HPI clear and ready to drive away.",
    features: [
      "Full Service History",
      "HPI Clear",
      "Leather Interior",
      "Heated Seats",
      "Sat Nav",
      "Parking Sensors",
      "Bluetooth",
      "Cruise Control",
    ],
    images: [],
    libraryImages: [],
    status: "available",
    featured: false,
    listedAt: "2026-05-02T01:25:31.959Z",
  },
  {
    id: "v002",
    slug: "mercedes-benz-ml63-amg-2006",
    title: "Mercedes-Benz ML63 AMG",
    make: "Mercedes-Benz",
    model: "ML63 AMG",
    year: 2006,
    mileage: 95000,
    price: 12000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    colour: "Silver",
    engine: "6.3L V8",
    interior: "Full leather",
    hpiClear: true,
    warrantyMonths: 0,
    ulezCompliant: null,
    description:
      "A rare and formidable ML63 AMG — Mercedes-Benz's most powerful ML of its era. The 6.3-litre naturally aspirated V8 delivers explosive performance in a commanding SUV body. This example presents well and offers extraordinary value for a true AMG icon.",
    features: [
      "6.3L V8 AMG Engine",
      "HPI Clear",
      "Full Leather",
      "AMG Sports Package",
      "Panoramic Roof",
      "Heated Seats",
      "Multi-Zone Climate Control",
      "Harman Kardon Sound",
    ],
    images: [],
    libraryImages: [],
    status: "available",
    featured: false,
    listedAt: "2026-05-02T01:25:31.959Z",
  },
];
